AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a # Replace with a valid AZ
      ImageId: ami-0123456789abcdef0 # Replace with a valid AMI ID
      InstanceType: t2.micro # Replace with a valid instance type
      KeyName: my-key-pair # Replace with your key pair
      SecurityGroupIds:
        - sg-0123456789abcdef0 # Replace with valid security group IDs
      SubnetId: subnet-0123456789abcdef0 # Replace with a valid subnet ID
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20 # Size in GB
            VolumeType: gp2
            DeleteOnTermination: true
      IamInstanceProfile: MyInstanceProfile # Replace with a valid IAM profile
      Monitoring: true
      Tags:
        - Key: Name
          Value: MyEC2Instance
      UserData: !Base64 |
        #!/bin/bash
        echo "Hello, World!" > /var/www/html/index.html